app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
// Route::get('/', 'HomeController@showWelcome');
Route::resource('/','WelcomeController');
Route::get('login',array(
		'as' => 'login_page',
		'uses' => 'SessionsController@create'
	));
Route::post('login',array(
		'as' => 'login_path',
		'uses' => 'SessionsController@store'
	));
Route::get('logout','SessionsController@destroy');
Route::controller('page','PagesController');
Route::get('download',function(){
	$file = $_GET['file'];
	return Response::download($file);
});
Route::get('view', function()
{
	$file = $_GET['file'];
	return Redirect::to($file);
});

// GROUP ROUTES

Route::group(array('before'=>'auth'), function(){
Route::resource('users','UsersController');
Route::resource('admin','AdminController');
Route::resource('admin.staffs','StaffsController');
Route::resource('admin.plots','PlotsController');
Route::resource('plots','PlotsController');
Route::resource('agents','AgentsController');
Route::resource('staffs','StaffsController');
Route::resource('payments','PaymentsController');
Route::resource('customers.payments','PaymentsController');
Route::resource('cocuments', 'DocumentsController');
Route::resource('customers', 'CustomersController');
Route::resource('agents.customers', 'CustomersController');
Route::resource('search', 'SearchController');
Route::resource('partners', 'PartnersController');
Route::resource('transactions', 'TransactionsController');
Route::resource('prospectives', 'ProspectivesController');
Route::resource('tenants', 'TenantsController');
Route::resource('tenants.payments', 'TenanPaymentsController');
Route::resource('land-lords', 'LandlordsController');
Route::resource('compounds', 'CompoundsController');
Route::resource('houses', 'HousesController');
Route::resource('notifications', 'NotificationsController');
Route::get('data-entry', array('as'=>'data_entry', 'uses'=>'PagesController@showData'));
Route::resource('estates', 'EstatesController');
Route::resource('estates.plots', 'EstatesController');
});
#THIS IS THE TESTING PART BELOW
// Event::listen('illuminate.query',function($query){
// echo '<pre style="margin:200px 80px">';
// print_r($query);
// echo '</pre>';
// });

app/models/Tenant.php
<?php

class Tenant extends \Eloquent {
	protected $primaryKey = 'tent_id';
	protected $fillable = [
'tent_id',
'tent_houseID',
'tent_compoundID',
'tent_rentID',
'tent_personid',
'tent_advance',
'tent_monthlyFee',
'tent_paymentStype',
'tent_status'  # 0 - left, 1 = mean occupying, 2 = pending to leave, 3 = owed rent before leaving; 4 = does not have a house
];

	public function house(){
		return $this->belongsTo('House','tent_houseID','hous_id');
	}
	public function person(){
		return $this->belongsTo('Person','tent_personid','id');
	}
	public function rents(){
		return $this->hasMany('Rent','rent_tenantID','tent_id');
	}
	public function documents(){
		return $this->hasMany('Document','entity_ID','tent_id');
	}
}

app/controllers/TenantsController.php
<?php

class TenantsController extends \AdminController {

	/**
	 * Display a listing of the resource.
	 * GET /tenants
	 *
	 * @return Response
	 */
	public function index()
	{
		// $all = House::with('tenants')->get();
		$all = Tenant::with('house','person.contacts')->get();
		$all = ($all)? $all->toArray() : [];
		$this->layout->content = View::make('admin.Tenants.index')->with('tenants',$all);
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /tenants/create
	 *
	 * @return Response
	 */
	public function create()
	{
		$data =  array();
		$houses = Compound::with(array('houses'=>function($query){
			$query->where('hous_status','=',0);
		}))->get();
 		$house = ( !empty($houses) )? $houses->toArray() : [];
 		$data['compounds'] = $house;
		$this->layout->content = View::make('admin.Tenants.create')->with('data', $data);
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /tenants
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$person = array();
		$staff = array();
		$address = array();
		$contact = array();
		$tent = array();
		$done = false;
		if ($input) :
			foreach ($input as $k => $table) {
				if (is_array($table)) {
					if ($k == 'person') {
						$V = new services\validators\Person($table);
						if($V->passes()){
							$person = Person::create(array(
							'pers_fname' => $table['fname'], 
							'pers_mname' => ($table['mname']) ?: null, 
							'pers_lname' => $table['lname'], 
							'pers_type' => 'Tenant', 
							'pers_DOB' => $table['dob'], 
							'pers_gender' => $table['Pers_Gender'], 
							'pers_nationality' => $table['Pers_Nationality'], 
							'pers_ethnicity' => $table['Pers_Ethnicity'], 
							'pers_NIN' => $table['nin_id'] 
							));
							if ($person->id) {
								$done = true;
							}
						}else{
							$errors = $V->errors;
							return Redirect::back()->withErrors($errors)->withInput();							
						}


					}
					if ($k == 'address') {
						$address = $table;
						if ($person->id) {
							$address = array_add($address, 'Addr_EntityID', $person->id);
							$address = array_add($address, 'Addr_EntityType', 'Person');
							$V = new services\validators\Address($table);
							if($V->passes()){
								$address = Address::create($address);
							}
						}
						$errors = $V->errors;

					}
					if ($k == 'contact') {

						

						if ($person->id) {

							$V = new services\validators\Contact($table);
							foreach ($table as $key => $value) {
								if($V->passes()){

									if(!empty($value)){
										$contact = Contact::create(array(
										'Cont_EntityID' => $person->id,	
										'Cont_EntityType' => 'Person',	
										'Cont_Contact' => $value,	
										'Cont_ContactType' =>  $key	
										));

									$contact = $contact->toArray();
									}
								}
							}
							$errors = $V->errors;
						}
					}

				}
			}
			if($done){

			if (!empty($input['houseID']) || !empty($input['Monthly_fee']) ) {


					$house = House::where('hous_id','=',$input['houseID'])->first();
					$house = (!empty($house))? $house->toArray() : [];
	
									
					if (!empty($house)) {
						$tent = Tenant::create(array(
								'tent_houseID'=> $input['houseID'],
								// 'tent_compoundID'=> $house['hous_compoundID'],
								'tent_advance'=> $input['down_payment'],
								'tent_personid'=> $person->id,
								'tent_status'=> 1
						));
					}else{

						$tent = Tenant::create(array(
								'tent_houseID'=> $input['houseID'],
								// 'tent_compoundID'=> $house['hous_compoundID'],
								'tent_advance'=> $input['down_payment'],
								'tent_personid'=> $person->id,
								'tent_status'=> 4 #does not have a house
						));	
									
					}

					// we add rent 
					$montlyfee = 0;   
					// dd($house);
					if( isset($input['Monthly_fee']) && !empty($input['Monthly_fee']) ):
						$montlyfee = $input['Monthly_fee'];
					else:
						if(!empty($house)):
		  					$montlyfee = $house['hous_price'] ;
		  				endif;
					endif;
					$ren = Rent::create(array(
						'rent_houseID' => $input['houseID'],
						'rent_tenantID' => $tent->tent_id,
						'rent_advance' => $input['down_payment'],
						'rent_firstmonthpaid' => null,
						'rent_nextpaydate' => null,
						'rent_monthlyFee' => $montlyfee
					));
					$house = House::find($input['houseID']);
					$tenanting = Tenant::find($tent->tent_id);
					if(!empty( $tenanting )):
						$tenanting->tent_rentID = $ren->rent_id;
						$tenanting->save();
					endif;

					if(!empty( $house )):
						$house->hous_status = 1;
						$house->save();
					endif;


	
			} #end of monthly fee and house


					if ($input['photo']) {


							$not = 'media'.DS.'Tenant'.DS.$person->pers_fname.'_'.$person->pers_mname.'_'.$person->pers_lname.'_'.$person->id;
							$foldername = DS.$not.DS;
							// $full_dir = $foldername.'img'.DS.'full';

							$path = base_path().$foldername ;
							$thumbnail_dir = $not.DS.'img'.DS.'thumbnail'.DS;
							$fileexten = Input::file('photo')->getClientOriginalExtension();
							$filename = Input::file('photo')->getClientOriginalName();
							$shortened = base_convert(rand(10000,99999), 10, 36);
							$rename = $person->pers_fname.'_'.$shortened.'_photo_.'.$filename;


							$filetyp = Input::file('photo')->getMimeType();

							$fileexten = Input::file('photo')->getClientOriginalExtension();
							$uploaded = false;

							if ((File::exists($path)) && ( File::exists( $path.DS.'img'.DS ) ) && ( File::exists( $path.DS.'img'.DS.'thumbnail') ) ) {
								Input::file('photo')->move($path.DS.'img'.DS, $rename);
									#notice #01
										// there was a problem when trying to resize the image. the fix is go in the project dir (html but ! include)

									// we resize (250 X 300)
									$img = Image::make($not.$rename);
									$img->resize(250 , 300);
									$img->save($thumbnail_dir.$rename);	// we move to thumnails

								// store in the database
								Document::create(array(
										'title' => 'profile picture' ,
										'entity_type' => 'Person',
										'entity_ID' => $person->id,
										'type' => 'Photo',
										'fullpath' => $path.DS.'img'.DS.$rename,
										'filename' => $filename,
										'foldername' => $not,
										'extension' => $fileexten,
										'filetype' => $filetyp,
										'thumnaildir' => $thumbnail_dir.$rename
									));
								
								# code...
							}else{
								File::exists($path) ?: mkdir($path,0777,true);
								File::exists($path.DS.'img'.DS) ?: mkdir($path.DS.'img'.DS,0777,true);
								File::exists($path.DS.'img'.DS.'thumbnail') ?: mkdir($path.DS.'img'.DS.'thumbnail',0777,true);
								Input::file('photo')->move($path.DS.'img'.DS , $rename);
									// we resize (250 X 300)
									// dd($not.DS.$rename);
									$img = Image::make($not.DS.'img'.DS.$rename);
									$img->resize(250 , 300);
									$img->save($thumbnail_dir.$rename);	// we move to thumnails

								// store in the database
								Document::create(array(
										'title' => 'profile picture' ,
										'entity_type' => 'Person',
										'entity_ID' => $person->id,
										'type' => 'Photo',
										'fullpath' =>  $path.DS.'img'.DS.$rename,
										'filename' => $filename,
										'foldername' => $not,
										'extension' => $fileexten,
										'filetype' => $filetyp,
										'thumnaildir' => $thumbnail_dir.$rename
									));
							}
					} #end of photo








				Flash::message("Successfully added a Tenant");
				return Redirect::back();
			}else{
				return Redirect::back()->withErrors($errors)->withInput();							
			}
		endif;
	}

	/**
	 * Display the specified resource.
	 * GET /tenants/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$all = Tenant::with('house.compound','person.contacts','person.addresses','rents.payments','person.documents')->whereRaw('tent_id = ? AND deleted = ?',[$id,0])->first();
		//$all = Tenant::with('house.compound','person.contacts','person.addresses','rents.payments')->whereRaw('tent_id = ? AND deleted = ? AND tent_status = ?',[$id,0,0])->first();
		$all = ($all)? $all->toArray() : [];
		// dd($all);
		$this->layout->content = View::make('admin.Tenants.show')->with('tenant',$all);
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /tenants/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$all = Tenant::with('house.compound','person.contacts','person.addresses','rents.payments','person.documents')->whereRaw('tent_id = ? AND deleted = ?',[$id,0])->first();
		//$all = Tenant::with('house.compound','person.contacts','person.addresses','rents.payments')->whereRaw('tent_id = ? AND deleted = ? AND tent_status = ?',[$id,0,0])->first();
		$all = ($all)? $all->toArray() : [];
		$this->layout->content = View::make('admin.Tenants.edit')->with('tenant',$all);
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /tenants/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{

		
	$input = Input::all();
		if($input['type'] == 'person'):
			$person = Person::findOrFail($input['person_id']);
			$person->fill($input);
			$person->save();
			return Redirect::back();
		endif;

		if($input['type'] == 'address'):

			$person = Address::findOrFail( $input['address_id'] );
			$person->fill($input);
			$person->save();
			return Redirect::back();	
		endif;

		if($input['type'] == 'contact'):

			$person = Contact::findOrFail( $input['contact_id'] );
			$person->fill($input);
			$person->save();
			return Redirect::back();

		endif;

		if($input['type'] == 'image'):

			$path = $path = base_path().DS.$input['foldername'] ; #notice 006 would fail if not set
			$not =  '';
			$foldername = '';
			$fn = '';
			if(starts_with($input['foldername'], '/')):

				$person = Document::find($input['image_id'])->person()->first();

app/views/admin/Tenants/edit.blade.php
<?php #page specific processing
    $image = array();
    $person =  array();
    $documents =  array();
    $compound = array();
    if (!empty($tenant)) {
        foreach ($tenant as $key => $value) {
           if ($key == 'person') {
              $person = $value;
           }
           if ($key == 'documents') {
               foreach ($value as $d => $doc) {
                    if ($doc['type'] == 'Photo') {
                       $image = $doc;
                    }else{
                        $documents[] = $doc;
                    }
               }
           }
           if ($key == 'compound') {
               $compounds = $value;
           }
           if ($key == 'kin') {
               $kin = $value;
           }
        }
    }
    $contacts = (!empty($person['contacts']))? $person['contacts'] : [];
    $addresses = (!empty($person['addresses']))? $person['addresses'] : [];
    if (!empty($person['documents'])) {
       foreach ($person['documents'] as $d => $doc) {
            if ($doc['type'] == 'Photo') {
               $image = $doc;
            }else{
                $documents[] = $doc;
            }
       }
    }
 ?>
@include('templates/top-admin')
@section('content')
   <div class="scope">
        <div class="hedacont">
            <div class="navbar">
                <div class="navbar-inner" id="scopebar">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target="navbar-responsive-collapse">
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </a>
                        <a class="brand" href="">Tenant Name : {{ucwords($tenant['person']['pers_fname'].' '.$tenant['person']['pers_mname'].' '.$tenant['person']['pers_lname'])}}</a>
                        <div class="nav-collapse collapse navbar-responsive-collapse">
                          <ul class="nav">  
                            <li><a href="#basic">General</a> </li>
                            <li><a href="#rent">Rent</a></li>
                            <li><a href="#payments">Payments</a></li>
                            <li><a href="{{route('houses.show')}}">House</a></li>
                            <li><a href="#notify">Notications</a></li>
                            <li><a href="#documents">Documents</a></li>
                            <li><a href="{{route('tenants.edit',$tenant['tent_id'])}}">Edit</a> </li>
                            <li class="divider-vertical"></li>
                            <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Options <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                @if(empty($tenant['tent_houseID']))
                                  <li><a href="#">Add to a house</a></li>
                                  @else
                                  <li><a href="#">Transfer to another house</a></li>
                                @endif
                              <li><a href="#">Vacate</a></li>
                              <li class="divider"></li>
                              <li><a href="#">Delete Records</a></li>
                            </ul>
                          </li>
                           </ul>
                        </div><!-- /.nav-collapse -->
                    </div>
                </div><!-- /navbar-inner -->
            </div> 
            <div class="c-header">
                <?php if (!empty($image)): ?>
                    <ul class="thumbnails" id="thmb">
                        <li class="span2">
                          <a href="#" class="thumbnail">
                           {{HTML::image($image['thumnaildir'])}}
                          </a>
                        </li>
                    </ul>                      
                <?php endif ?>

            </div>          
        </div>  
    </div>  <!-- end of scope -->

    <div class="content-details clearfix">
    	<div class="cc clearfix">
    		<h3>Editing Tenant</h3>
    		<hr>

	        <ul class="thumbnails">
	          <li class="row">
	            <div class="thumbnail">
	              <div class="caption">
	                <h3>Edit Personal</h3>
	                <hr>
				{{Form::model($person, ['route'=>[ 'tenants.update' , $tenant['tent_id']  ], 'method'=>'PATCH'],['class'=>'form-snippet'])}}

					<div class="level details">

						<div class="first">
							<div>
								{{Form::label('pers_fname','First Name')}}
								{{Form::text('pers_fname',null,['class'=>'input-xlarge','placeholder'=>'Enter first name','required'=>1])}}
							</div>
							<div>
								{{Form::label('pers_mname','Middle Name')}}
								{{Form::text('pers_mname',null,['class'=>'input-xlarge','placeholder'=>'Enter middle name'])}}
							</div>
							<div>
								{{Form::label('pers_lname','Last Name')}}
								{{Form::text('pers_lname',null,['class'=>'input-xlarge','placeholder'=>'Enter last name','required'=>1])}}
							</div>							
						</div>
					</div>
					<div class="level details">
						<span>Bio </span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('pers_DOB','Birthday ( year-month-day )')}}
								{{Form::text('pers_DOB',null,['class'=>'input-xlarge' ])}}
							</div>
							<div>
								{{Form::label('pers_ethnicity','Ethniticity')}}
								<select name="pers_ethnicity" id="enit" class="input-xlarge">
									<?php $countries = Variable::domain('Pers_Ethnicity')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select>
							</div>
							<div>
								{{Form::label('pers_nationality','Nationality')}}
								<select name="pers_nationality" id="nation" class="input-xlarge">
									<?php $countries = Variable::domain('Country')->toArray();  ?>
									@foreach ($countries as $key => $country)
									<option>{{$country['Vari_VariableName']}}</option>
									@endforeach
								</select>
							</div>
							<div>
								{{Form::label('pers_gender','Gender')}}
								{{Form::select('pers_gender', array('male' => 'Male','female' => 'Female'));}}
							</div>
						</div>
					</div>

					<div class="level details">
						<span>Identification details</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('pers_NIN','Nation id number / passport number')}}
								{{Form::text('pers_NIN',null,['class'=>'input-xlarge span6','placeholder'=>'NIN number or passport number'])}} 
							</div>
						</div>
					</div>

	                <hr>
					{{Form::hidden('type','person')}} 
					{{Form::hidden('person_id',$person['id'])}} 
	                <button class="btn btn-primary">Save Changes</button>
					<button type="reset" class="btn">reset</button>
	              </div>
	            </div>
	            {{Form::close()}}
	          </li>  
	          
	        </ul>
	        <ul class="thumbnails">
<li class="span7">
	            <div class="thumbnail">
	              <div class="caption">
	                <h3>Edit Address</h3>
	                <hr>
						{{Form::model($person['addresses'][0], ['route'=>[ 'tenants.update' , $person['addresses'][0]['Addr_AddressID'] ], 'method'=>'PATCH'],['class'=>'form-snippet'])}}
						<div class="level details">
							<span>Address</span>
							<hr>
							<div class="first ">
								<div>
									{{Form::label('Addr_Town','Town')}}
									{{Form::text('Addr_Town',null,['class'=>'input-xlarge','placeholder'=>'Enter town'])}}
								</div>
								<div>
									{{Form::label('Addr_District','District')}}
									<select name="Addr_District" id="region">
										<?php $countries = Variable::domain('Addr_District')->toArray();  ?>
										@foreach ($countries as $key => $country)
										<option>{{$country['Vari_VariableName']}}</option>
										@endforeach
									</select> 
								</div>
								<div>
									{{Form::label('Addr_AddressStreet','street')}}
									{{Form::text('Addr_AddressStreet',null,['class'=>'input-xlarge','placeholder'=>'Enter street'])}}
								</div>
							</div>
						</div>
	                <hr>
	                {{Form::hidden('type','address')}} 
					{{Form::hidden('address_id', $person['addresses'][0]['Addr_AddressID'] )}} 
	                <button class="btn btn-primary">Save Changes</button>
					<button type="reset" class="btn">reset</button>
	              </div>
	            </div>
	            {{Form::close()}}
	          </li> 
	          <li class="span7">
	            <div class="thumbnail">
      			{{HTML::image($image['thumnaildir'])}}
	              <div class="caption">
				{{Form::model($image, ['route'=>['tenants.update', $tenant['tent_id'] ], 'files'=>true,'method'=>'PATCH'],['class'=>'form-snippet'])}}
					{{Form::hidden('foldername')}}
					{{Form::hidden('fullpath')}}
					{{Form::hidden('thumnaildir')}}
					<div class="level details">
						<span>Profile picture</span>
						<hr>
						<div class="first ">
							<div>
								{{Form::label('photo','Photo')}}
								{{Form::file('photo')}}
							</div>	
						</div>
					</div>

	                <hr>
	                {{Form::hidden('type','image')}} 
					{{Form::hidden('image_id', $image['id'])}} 
	                <button class="btn btn-primary">Save Changes</button>
					<button type="reset" class="btn">reset</button>
	           
	              </div>
	            </div>
	             {{Form::close()}}
	          </li>   
	        </ul>
    	</div>
	</div>
@stop
@include('templates/bottom-admin')

app/views/admin/Tenants/index.blade.php
@include('templates/top-admin')
@section('content')
@include('__partials/modal-add-tenant')
	<div class="c-header cc">
		<h3>Tenants <!-- <a href="#myModal" role="button" data-toggle="modal"><i class="fa fa-plus"></i> --></a></h3>
	</div>
	<div class="cc">
				<table class="table">
					<thead>
						<tr>
							<th>Fullname</th>
							<th>Nationality</th>
							<th>Gender</th>
							<th>House number</th>
							<th>House price</th>
							<th>created</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						<?php if (!empty($tenants)): ?>
							<?php foreach ($tenants as $key => $value): ?>
							<tr>
								<td>
									<a href="{{route('tenants.show',$value['tent_id'])}}">
									{{ucwords(e($value['person']['pers_fname'].' '.$value['person']['pers_mname'].' '.$value['person']['pers_lname']))}}
									</a>								
								</td>
								<td>
									{{ucwords(e($value['person']['pers_nationality']))}}
								</td>
								<td>
									{{ucwords(e($value['person']['pers_gender']))}}
								</td>
								<td>
									{{ucwords(e($value['house']['hous_number']))}}
								</td>
								<td>
									{{ucwords(e($value['house']['hous_price']))}}
								</td>
								<td>
									{{ucwords(e($value['created_at']))}}
								</td>
								<td>
									<a href="{{route('tenants.show',$value['tent_id'])}}">view</a> | 
									<a href="{{route('tenants.destroy',$value['tent_id'])}}" class="dropdown-toggle"  data-toggle="dropdown">
										Options
										<!-- <span class="caret"></span> -->
									</a>
									  <ul class="dropdown-menu">
									    <!-- dropdown menu links -->
									    <li>
									    	{{Form::delete('tenants/'. $value['tent_id'], 'Delete')}}
									    </li>
									  </ul>
								</td>
							</tr>						
							<?php endforeach ?>
							<?php else: ?>
							<tr>
								<td colspan="8"><h4>No Tenance Available!</h4></td>
							</tr>
						<?php endif ?>
					</tbody>
				</table>

		  </div>
		</div>
	</div>
@stop
@include('templates/bottom-admin')